# Generated by Django 5.1.5 on 2026-05-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('registrationType', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mobilenumber', models.BigIntegerField(null=True, unique=True)),
                ('houseno', models.CharField(max_length=200)),
                ('emailaddress', models.EmailField(max_length=254, unique=True)),
                ('pincode', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=200)),
                ('maintenance_activity', models.TextField()),
                ('outage_affected_area', models.TextField()),
                ('outage_area', models.TextField()),
                ('outage_start_date', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=50)),
                ('outage_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='outagenotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('issueType', models.CharField(choices=[(' voltage', ' Voltage Fluctuation'), ('no-supply', 'No Power Supply'), ('low-voltage', 'Low Voltage'), ('meter-issue', ' Meter Issue'), ('sparking', 'Sparking in Line'), ('line-down', 'Line Down'), ('scheduled-maintenance', 'Scheduled Maintenance'), ('others', 'Others')], max_length=200)),
                ('issueDateTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
